### ISSUE TITLE
Issue with height and crop when upsizing then downsizing viewport. 

### ISSUE THREAD

**Issue by olemarius** [imazen/slimmage#23]
When using height param and sizing the viewport up, then down again, the large scale image is still used and the height will be less than I asked for (400 as in example below). 

```<img class="slimmage" src="blah.jpg?width=800&height=400&scale=both&mode=crop&slimmage=true&quality=90" />```

**Comment by nathanaeljones** [comment]
`height` is now supported in the `unstable` branch. Please test and let us know if you have any more issues!
