### ISSUE TITLE
Incorrect image width if parent of image have display:none

### ISSUE THREAD

**Issue by abadyl** [imazen/slimmage#28]
I applied slimmage to our website and found that width of image is 0 when parent of image have style display:none 
line 45:  var pixels = temp.offsetWidth; This is correct behavior of browser, but I think slimmage should have workaround of it.

We experienced it for images which used together with jquery.cycle2 plugin.

For now we solve our problem  by the following:
1. Placed slimmage.js as first script before </body>
2. We run processing image immediately after HTML was loaded and parsed by browser (not after DOMContentLoaded, load events);
window.slimmage.checkResponsiveImages();
3. In this case I am sure not one plugin who can set display:none to parent willn't broke width calculations.

**Comment by nathanaeljones** [comment]
The only correct solution, AFAIK, is to (a) try to get slimmage to execute first, and (b) call `window.slimmage.checkResponsiveImages()` each time after you manipulate the DOM. It will [be a long time before we can drop support for IE10](http://caniuse.com/#feat=mutationobserver) and rely exclusively on MutationObserver to do our cleanup for us..
