### ISSUE TITLE
Android Chrome Fires readyCallback on scroll

### ISSUE THREAD

**Issue by Jeavon** [imazen/slimmage#31]
While not really a bug in Slimmage maybe a workaround could be applied so that readyCallBack is only fired once, this issue is due to mobile Chrome firing the resize event on scroll. More details http://stackoverflow.com/questions/17328742/mobile-chrome-fires-resize-event-on-scroll and http://stackoverflow.com/questions/9361968/javascript-resize-event-on-scroll-mobile

**Comment by nathanaeljones** [comment]
Or, can we detect devices that do this via feature detection, and use onOrientationChange instead?

**Comment by nathanaeljones** [comment]
@Jeavon, here are some possible solutions:

1. Set a flag if any changes are actually made to images. Fire a separate event if this happens, like 'imageUpdated'.

2. Create a new event, or modify the semantics of readyCallback to occur only when changes have been made to the DOM - OR - on first call to `checkResponsiveImages`().

I don't have as much mobile web experience as you, so I'd like to get your opinion on the best solution before implementing. I'd like to release 0.4.0 with height support soon, addressing this at the same time could be nice.

**Comment by Jeavon** [comment]
Wow, I had forgotten about this issue! I would go for number two, have readyCallBack only fire when changes have been made as I don't think there's any reason to execute anything is nothing has been changed...
