### ISSUE TITLE
Slimmage with slideshows

### ISSUE THREAD

**Issue by mwentz** [imazen/slimmage#4]
I am trying to use Slimmage and SlimResponse (with ImageResizer) with jquery Cycle2. Slimming is happening after Cycle2 is being initialized which is causing various issues. Depending on how I set up the slideshow and css, I am getting either no slideshow or the images after the first one are 160px.

I have the same issue with the Bootstrap Carousel, all the images after the first one are 160px. I'm guessing this is happening because the of the display:none on all but the first image.

**Comment by 36lpi** [comment]
Hello!

I'm dusting this thread off...

I'm facing a very similar issue as mwentz did, and I've been following the thread to solve it. 

We're using ImageResizer along with Slimmage, and serving the images in a Cycle 2 slideshow. I know the images are being rendered, but they're not showing up for me.

I just want to confirm whether or not your fiddle is still valid. I took a look at it, and the results are empty—which is what I'm getting too. ;)

Thanks in advance.

**Comment by nathanaeljones** [comment]
The approach is still valid, but ensure you use the latest version of slimmage.
