### ISSUE TITLE
Slimmage v0.4.1 not updating the src attribute on images on upgraded sites

### ISSUE THREAD

**Issue by Jeavon** [imazen/slimmage#48]
I'm not exactly sure why but Slimmage v0.4.1 is not working on some upgrades. The issue is that getCssValue is returning null. This is because val is "none" and the is_blank returns false for this.
I've tested in Chrome 40 and Firefox.
If I remove the `v === "none" ||` from the is_blank method everything works again...
Any ideas?

**Comment by Jeavon** [comment]
Ok, tracked it down. The images didn't have a max-width:100% adding it fixes it. I guess it might be a breaking change as v0.2.x worked without requiring it...?

**Comment by nathanaeljones** [comment]
What would you expect the behavior to be if there is no max-width?

**Comment by Jeavon** [comment]
In v0.2.x it used width so I would expect it to use width if no max-width...?

**Comment by nathanaeljones** [comment]
Both 0.4.x and 0.2.x only query 'max-width'. They do read the value by applying it to a div, and checking the offsetWidth. 

https://github.com/imazen/slimmage/blob/support/v0.2/slimmage.js#L108
https://github.com/imazen/slimmage/blob/master/slimmage.js#L203

0.2.X incorrectly parsed 'none' on some browsers, and it's likely that this often produced the equivalent of max-width:100%. It wouldn't have fallen back to the value of the image width, in *any* case. The image's container, well, that would be involved.

Actually reading the width of an image is fundamentally impossible on many browsers. Sizing things based on the behavior of a div you drop into the DOM is tricky enough when you give it a 'max-width'. 

We'd be better off explicitly providing a fallback value for 'max-width' than relying on the coincidence that made this work in 0.2.x.

**Comment by nathanaeljones** [comment]
Perhaps this is something we should document? Given that a CSS rule 'fixes it', `img.slimmage {max-width:100%;}`, I'm hesitant to make a behavior change here.

**Comment by Jeavon** [comment]
Totally agree, it should be documented (it is now above). Nothing needs to be changed in the code base.
