### ISSUE TITLE
Img tag inside of noscript is being encoded

### ISSUE THREAD

**Issue by michaelpontin** [imazen/slimmage#52]
If you turn javascript off the img tag inside of the noscript tag is being html encoded and so gets output as a string rather than an image.

**Comment by ruant** [comment]
@michaelpontin I have javascript on, but I get the img tag encoded. Any suggestions?

**Comment by hannah123** [comment]
Did you find a solution for this ?

**Comment by nathanaeljones** [comment]
I think this only happens if your HTML starts out as HTML encoded; this isn't a bug in slimmage, but rather a bug in the code creating the HTML (if my assumption is correct).
