### ISSUE TITLE
Question: Updating images when user pinch-zooms on mobile browsers

### ISSUE THREAD

**Issue by DhyanMikael** [imazen/slimmage#54]
Images are not being updated when a user zooms into a webpage with pinch gesture.

Is there a possibility or work-around to achieve this?

**Comment by nathanaeljones** [comment]
Zooming shouldn't create network requests and risk UI freezes as assets are replaced. Some rendering engines actually prevent this.  

We don't want to make changes in response to a pinch zoom.
